### ISSUE TITLE
Dead by Daylight not injecting / working

### ISSUE THREAD

**Issue by harlooo** [MilkyDeveloper/ReshadeForUWP#11]
It doesn't seem to work on Dead By Daylight, is there something I might be doing wrong?

**Comment by MilkyDeveloper** [comment]
I think this is fairly straight forward. Dead by Daylight uses Easy Anti Cheat (EAC), and EAC has a whitelist for Reshade, meaning it should work. However, setting it up normally would compose of moving a DLL to the game executable folder. Windows handles this injection, and EAC allows this kind of injection and has a whitelist for Reshade. However, this project externally injects it because UWP apps don't have the same DLL injection functionality. EAC is possibly protecting the game's memory from this being injected, because it thinks it is a traditional game cheat. I can't think of any fix off the top of my head.

**Comment by ButtersTech** [comment]
Now that the Xbox app lets you move the game files it could be worth another look. just for example i can now use the DBD Icon Toolbox to change the icons in the game. When the files were in the WindowsApps folder it didnt work, even after taking ownership of the whole directory. 

I couldnt get reshade to work but it would be awesome if it worked since we also cant use Nvidia Filters with this version of the game for some reason. 

I understand if its not worth your time to look into though.

**Comment by harlooo** [comment]
Hey, I never expected you to look more into this haha, I will definitely
give it a look as soon as I fix my pc, I recently messed up something in
the bios and now windows won’t boot (I’m a big noob)

**Comment by ButtersTech** [comment]
I'm not the dev, i was hoping to just throw out the idea to the dev. Unfortunately the Xbox app is just scuffed and the DBD experience will be lacking until BHVR lets us move to another platform and keep our saves. It's a bit odd that its not cross progression at this point.

**Comment by harlooo** [comment]
Makes sense, and yeah I 100% agree, atm I just play the game on steam
instead of Xbox app, I don’t think we’ll ever get cross progression at this
point

**Comment by AntiDreams** [comment]
yeah and cross progression isn't even on their plans this year
