### ISSUE TITLE
Minecraft bedrock not working

### ISSUE THREAD

**Issue by SensoryWolf** [MilkyDeveloper/ReshadeForUWP#13]
i did everything u did in video but my mc bedrock doesn't work when I click home button it doesn't open overlay

**Comment by MilkyDeveloper** [comment]
Minecraft Bedrock doesn't really work because it was made specifically for the Microsoft Store. In other words, it's quite hard to inject Reshade in it. It embeds itself in something called *ApplicationFrameHost*, which is a big reason why this is so hard. Within this month or so, I might get something working, but for now, I'm closing the issue.
