### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by nowwhat1** [MilkyDeveloper/ReshadeForUWP#6]
When i launch the .exe nothing happens, except i get the prompt for outgoing internet connection. No GUI, nothing... How does this work? o_O

**Comment by nowwhat1** [comment]
Got logs from Event Viewer. 
https://pastebin.com/UqhEDm63
https://pastebin.com/M3vVsvxU

Any help?

**Comment by MilkyDeveloper** [comment]
Alright, not really sure about this. On my fresh Windows install i'm not getting anything like this. I do notice one thing though: it's using NET 4.0 something instead of 4.7.2, which this project is made for. Download the runtime from here: https://dotnet.microsoft.com/download/dotnet-framework/net472
